theme: jekyll-theme-minimal
title: Sros's homepage
description: # ğŸŒŸ Lead Java Backend Engineer | Digital Banking & FinTech ğŸš€

Hi! Iâ€™m a **Lead Java Backend Engineer** at [Mbanq](https://mbanq.com/), specializing in **Java**, **Spring Boot**, and **microservices**. I design scalable systems, optimize performance, and lead teams to build cutting-edge digital banking solutions.

---

## ğŸ† Highlights
- Architected systems serving millions globally.  
- Reduced latency by 40% through performance tuning.  
- Led and mentored high-performing teams.

---

## ğŸ¤ Connect
- **LinkedIn**: [Sros](https://www.linkedin.com/in/sros-yort/)  
- **Email**: yortsros@gmail.com

â­ï¸ *Explore my work and let's innovate together!*
